apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
spec:
  type: ClusterIP
  selector:
    {{- include "app-helm-files.selectorLabels" . | nindent 4 }}
  ports:
    - name: metric
      port: 9464
      targetPort: 9464
  
     