# name: Build and Deploy Docker Image

# on:
#   pull_request:
#     types: [closed]

# jobs:
#   build_and_push:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Build and Push Docker Image
#         run: |
#           TAG="${GITHUB_SHA::8}"
#           docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$TAG .
#           docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$TAG
#         env:
#           GITHUB_SHA: ${{ github.sha }}

#       - name: Update Argo CD Manifest
#         run: |
#           TAG="${GITHUB_SHA::8}"
#           sed -i "s|image:.*|image: ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$TAG|g" path/to/argo-app/deployment.yaml
#           git config --global user.name "${{ github.actor }}"
#           git config --global user.email "${{ github.actor }}@users.noreply.github.com"
#           git checkout -b update-image-${TAG}
#           git add path/to/argo-app/deployment.yaml
#           git commit -m "Update image to $TAG"
#           git push origin update-image-${TAG}

#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v5
#         with:
#           branch: update-image-${{ github.sha }}
#           title: Update Docker image to ${{ github.sha }}
#           body: "This PR updates the Docker image in the Argo CD manifest to ${{ github.sha }}."
